const UNITS = [
  {id:0,name:'Pre-curso',accent:'cyan',
   classes:[
    {n:0,title:'Introduccion a Python, APIs y FastAPI',desc:'Python basico, HTTP, APIs, REST, primera app FastAPI, Swagger.',
     tags:['Python','HTTP','API','REST','FastAPI','Swagger'],dir:'semana-00-introduccion-python-fastapi',
     slides:'html/index.html',doc:'clase-00.md',
     example:'ejemplo-guiado/api-videojuegos.md',
     ex:'ejercicios/ejercicios-clase-00.md',faq:'dudas/preguntas-frecuentes.md'},
   ]},
  {id:1,name:'Fundamentos MVC y Frameworks',accent:'cyan',
   classes:[
    {n:1,title:'Introduccion al curso',desc:'HTTP, REST, cliente-servidor. Diagnostico y fundamentos.',
     tags:['HTTP','REST','API','Swagger'],dir:'semana-01-introduccion-al-curso',
     slides:'html/index.html',doc:'clase-01.md',
     example:'ejemplo-guiado/consumir-api-publica-python.md',
     ex:'ejercicios/ejercicios-clase-01.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:2,title:'Concepto, componentes e interaccion del patron MVC',desc:'Patron MVC, componentes, interaccion y equivalencia en FastAPI.',
     tags:['MVC','Patrones','Arquitectura'],dir:'semana-02-concepto-componentes-mvc',
     slides:'html/index.html',doc:'clase-02.md',
     example:'ejemplo-guiado/api-cursos-por-capas.md',
     ex:'ejercicios/ejercicios-clase-02.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:3,title:'Separacion de responsabilidades',desc:'Separacion de capas, organizacion de aplicaciones web mediante MVC.',
     tags:['SRP','Capas','Organizacion'],dir:'semana-03-separacion-responsabilidades',
     slides:'html/index.html',doc:'clase-03.md',
     example:'ejemplo-guiado/',
     ex:'ejercicios/',faq:'dudas/preguntas-frecuentes.md'},
    {n:4,title:'Frameworks web: conceptos, ventajas y limitaciones',desc:'Análisis comparativo de frameworks. Caracteristicas, ventajas y limitaciones.',
     tags:['FastAPI','Django','Flask','Benchmarks'],dir:'semana-04-frameworks-web',
     slides:'html/index.html',doc:'clase-03.md',
     example:'ejemplo-guiado/matriz-decision-frameworks.md',
     ex:'ejercicios/ejercicios-clase-03.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:5,title:'Parcial 1',desc:'Examen: MVC y Frameworks (semanas 1-4).',
     tags:['Parcial','MVC','Frameworks'],dir:'semana-05-parcial-1',
     slides:'html/index.html',doc:'spec-parcial-1.md',
     example:'',
     ex:'',faq:''},
   ]},
  {id:2,name:'FastAPI Fundamentals',accent:'blue',
   classes:[
    {n:6,title:'Seleccion de un framework especifico',desc:'Justificacion tecnica de FastAPI como framework del curso.',
     tags:['FastAPI','Seleccion','Justificacion'],dir:'semana-06-seleccion-framework',
     slides:'html/index.html',doc:'clase-06.md',
     example:'ejemplo-guiado/',
     ex:'ejercicios/',faq:'dudas/preguntas-frecuentes.md'},
    {n:7,title:'Instalacion y configuracion del framework',desc:'Entorno virtual, pip, Uvicorn, configuracion inicial.',
     tags:['Instalacion','Uvicorn','pip','venv'],dir:'semana-07-instalacion-configuracion',
     slides:'html/index.html',doc:'clase-04.md',
     example:'ejemplo-guiado/primer-proyecto-fastapi.md',
     ex:'ejercicios/ejercicios-clase-04.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:8,title:'Estructura y organizacion de proyecto',desc:'Organizacion: routers, schemas, servicios, core. Modularidad.',
     tags:['Modularidad','APIRouter','Estructura'],dir:'semana-08-estructura-proyecto',
     slides:'html/index.html',doc:'clase-05.md',
     example:'ejemplo-guiado/proyecto-modular-fastapi.md',
     ex:'ejercicios/ejercicios-clase-05.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:9,title:'Creacion y configuracion de app basica',desc:'Pydantic v2, validacion, schemas, primer endpoint funcional.',
     tags:['Pydantic','Validacion','Schemas','Endpoints'],dir:'semana-09-app-basica',
     slides:'html/index.html',doc:'clase-06-apirouter.md',
     example:'ejemplo-guiado/ejemplo-biblioteca-api.md',
     ex:'ejercicios/ejercicios-clase-06.md',faq:'dudas/dudas-frecuentes.md'},
    {n:10,title:'Ejecucion y validacion de la aplicacion',desc:'Uvicorn, JWT, middleware, CORS, manejo de errores.',
     tags:['Uvicorn','JWT','Middleware','CORS'],dir:'semana-10-ejecucion-validacion',
     slides:'html/index.html',doc:'clase-09-autenticacion-seguridad.md',
     example:'ejemplo-guiado/ejemplo-autenticacion-jwt.md',
     ex:'ejercicios/ejercicios-clase-09.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:11,title:'Parcial 2',desc:'Examen: FastAPI Fundamentals (semanas 6-10).',
     tags:['Parcial','FastAPI','Pydantic'],dir:'semana-11-parcial-2',
     slides:'html/index.html',doc:'spec-parcial-2.md',
     example:'',
     ex:'',faq:''},
   ]},
  {id:3,name:'FastAPI Intermedio',accent:'purple',
   classes:[
    {n:12,title:'Creacion y manejo de rutas',desc:'APIRouter, path params, query params, HTTP methods, CRUD.',
     tags:['APIRouter','Rutas','CRUD','HTTP'],dir:'semana-12-creacion-rutas',
     slides:'html/index.html',doc:'clase-12.md',
     example:'ejemplo-guiado/',
     ex:'ejercicios/',faq:'dudas/preguntas-frecuentes.md'},
    {n:13,title:'Routers, logica de negocio y SQLAlchemy',desc:'Routers como controllers, Depends, SQLAlchemy, relaciones.',
     tags:['Routers','SQLAlchemy','Depends','Relaciones'],dir:'semana-13-routers-logica-negocio',
     slides:'html/index.html',doc:'clase-07-persistencia-sqlalchemy.md',
     example:'ejemplo-guiado/ejemplo-persistencia-sqlalchemy.md',
     ex:'ejercicios/ejercicios-clase-07.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:14,title:'Motores de plantillas y testing',desc:'pytest, TestClient, fixtures, cobertura, TDD.',
     tags:['pytest','TestClient','Coverage','TDD'],dir:'semana-14-plantillas-presentacion',
     slides:'html/index.html',doc:'clase-11-testing-pytest.md',
     example:'ejemplo-guiado/ejemplo-testing-api.md',
     ex:'ejercicios/ejercicios-clase-11.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:15,title:'Parcial 3',desc:'Examen: FastAPI Completo (semanas 12-14).',
     tags:['Parcial','Rutas','Testing','SQLAlchemy'],dir:'semana-15-parcial-3',
     slides:'html/index.html',doc:'spec-parcial-3.md',
     example:'',
     ex:'',faq:''},
   ]},
  {id:4,name:'Cierre del Curso',accent:'green',
   classes:[
    {n:16,title:'Retroalimentacion y despliegue',desc:'pydantic-settings, Supabase, Render, despliegue final.',
     tags:['Render','Supabase','Deploy','CI/CD'],dir:'semana-16-retroalimentacion-cierre',
     slides:'html/index.html',doc:'clase-12-despliegue-render-supabase.md',
     example:'ejemplo-guiado/ejemplo-despliegue.md',
     ex:'ejercicios/ejercicios-clase-12.md',faq:'dudas/preguntas-frecuentes.md'},
   ]},
];

const RESOURCES = [
  {cat:'FastAPI',links:[
    {l:'Documentacion oficial',u:'https://fastapi.tiangolo.com/'},
    {l:'Tutorial completo',u:'https://fastapi.tiangolo.com/tutorial/'},
    {l:'Guia avanzada',u:'https://fastapi.tiangolo.com/advanced/'},
    {l:'Despliegue',u:'https://fastapi.tiangolo.com/deployment/'},
  ]},
  {cat:'Pydantic',links:[
    {l:'Documentacion oficial',u:'https://docs.pydantic.dev/'},
    {l:'Validadores',u:'https://docs.pydantic.dev/latest/concepts/validators/'},
    {l:'Configuracion',u:'https://docs.pydantic.dev/latest/api/config/'},
  ]},
  {cat:'SQLAlchemy',links:[
    {l:'Documentacion ORM',u:'https://docs.sqlalchemy.org/'},
    {l:'Quick Start',u:'https://docs.sqlalchemy.org/en/20/orm/quickstart.html'},
    {l:'Relaciones',u:'https://docs.sqlalchemy.org/en/20/orm/relationships.html'},
    {l:'Alembic',u:'https://alembic.sqlalchemy.org/'},
  ]},
  {cat:'Autenticacion',links:[
    {l:'Introduccion a JWT',u:'https://jwt.io/introduction'},
    {l:'Seguridad FastAPI',u:'https://fastapi.tiangolo.com/tutorial/security/'},
    {l:'passlib',u:'https://passlib.readthedocs.io/'},
  ]},
  {cat:'Infraestructura',links:[
    {l:'Render Docs',u:'https://render.com/docs'},
    {l:'Supabase Docs',u:'https://supabase.com/docs'},
    {l:'FastAPI Deployment',u:'https://fastapi.tiangolo.com/deployment/'},
    {l:'Uvicorn Settings',u:'https://www.uvicorn.org/settings/'},
  ]},
  {cat:'Estandares',links:[
    {l:'MDN HTTP',u:'https://developer.mozilla.org/es/docs/Web/HTTP'},
    {l:'OWASP API Security',u:'https://owasp.org/API-Security/'},
    {l:'Python Packaging',u:'https://packaging.python.org/'},
  ]},
];
