const UNITS = [
  {id:1,name:'Fundamentos',accent:'cyan',
   classes:[
    {n:1,title:'Marco de aplicaciones web modernas',desc:'HTTP, REST, cliente-servidor. Diagnóstico y fundamentos.',
     tags:['HTTP','REST','API','Cliente-servidor'],dir:'clase-01-marco-aplicaciones-web-modernas',
     slides:'html/index.html',doc:'clase-01.md',
     example:'ejemplo-guiado/consumir-api-publica-python.md',
     ex:'ejercicios/ejercicios-clase-01.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:2,title:'MVC, patrones y FastAPI',desc:'Patrón MVC, equivalencia arquitectónica en FastAPI.',
     tags:['MVC','Patrones','Arquitectura'],dir:'clase-02-mvc-patrones-fastapi',
     slides:'html/index.html',doc:'clase-02.md',
     example:'ejemplo-guiado/api-cursos-por-capas.md',
     ex:'ejercicios/ejercicios-clase-02.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:3,title:'Frameworks: comparación y elección',desc:'Análisis comparativo de frameworks. ¿Por qué FastAPI?',
     tags:['FastAPI','Django','Flask','Benchmarks'],dir:'clase-03-frameworks-comparacion-eleccion',
     slides:'html/index.html',doc:'clase-03.md',
     example:'ejemplo-guiado/matriz-decision-frameworks.md',
     ex:'ejercicios/ejercicios-clase-03.md',faq:'dudas/preguntas-frecuentes.md'},
   ]},
  {id:2,name:'Desarrollo con FastAPI',accent:'blue',
   classes:[
    {n:4,title:'Instalación y primer proyecto',desc:'Entorno virtual, instalación, primer endpoint FastAPI.',
     tags:['Instalación','Uvicorn','Rutas'],dir:'clase-04-instalacion-primer-proyecto',
     slides:'html/index.html',doc:'clase-04.md',
     example:'ejemplo-guiado/primer-proyecto-fastapi.md',
     ex:'ejercicios/ejercicios-clase-04.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:5,title:'Estructura profesional',desc:'Organización: routers, schemas, servicios, core.',
     tags:['Modularidad','APIRouter','Estructura'],dir:'clase-05-estructura-profesional-proyecto',
     slides:'html/index.html',doc:'clase-05.md',
     example:'ejemplo-guiado/proyecto-modular-fastapi.md',
     ex:'ejercicios/ejercicios-clase-05.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:6,title:'Modelos Pydantic y validación',desc:'Validación con Pydantic v2: Field, tipos, errores.',
     tags:['Pydantic','Validación','Schemas'],dir:'clase-06-modelos-pydantic-validacion',
     slides:'html/index.html',doc:'clase-06-apirouter.md',
     example:'ejemplo-guiado/ejemplo-biblioteca-api.md',
     ex:'ejercicios/ejercicios-clase-06.md',faq:'dudas/dudas-frecuentes.md'},
    {n:7,title:'Persistencia con SQLAlchemy',desc:'ORM, Session, CRUD real con SQLite. Modelos.',
     tags:['SQLAlchemy','ORM','CRUD','SQLite'],dir:'clase-07-persistencia-sqlalchemy',
     slides:'html/index.html',doc:'clase-07-persistencia-sqlalchemy.md',
     example:'ejemplo-guiado/ejemplo-persistencia-sqlalchemy.md',
     ex:'ejercicios/ejercicios-clase-07.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:8,title:'Relaciones entre modelos',desc:'Foreign Keys, relationships, joins, eager/lazy loading.',
     tags:['Relaciones','FK','Joins','M:N'],dir:'clase-08-relaciones-sqlalchemy',
     slides:'html/index.html',doc:'clase-08-relaciones-sqlalchemy.md',
     example:'ejemplo-guiado/ejemplo-relaciones-sqlalchemy.md',
     ex:'ejercicios/ejercicios-clase-08.md',faq:'dudas/preguntas-frecuentes.md'},
   ]},
  {id:3,name:'Calidad y Seguridad',accent:'purple',
   classes:[
    {n:9,title:'Autenticación con JWT',desc:'OAuth2, tokens JWT, bcrypt, rutas protegidas, roles.',
     tags:['JWT','OAuth2','bcrypt','Roles'],dir:'clase-09-autenticacion-seguridad',
     slides:'html/index.html',doc:'clase-09-autenticacion-seguridad.md',
     example:'ejemplo-guiado/ejemplo-autenticacion-jwt.md',
     ex:'ejercicios/ejercicios-clase-09.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:10,title:'Middleware, CORS y errores',desc:'Middleware personalizado, CORS, manejo global de excepciones.',
     tags:['Middleware','CORS','Errores','Lifespan'],dir:'clase-10-middleware-cors-errores',
     slides:'html/index.html',doc:'clase-10-middleware-cors-errores.md',
     example:'ejemplo-guiado/ejemplo-middleware-cors.md',
     ex:'ejercicios/ejercicios-clase-10.md',faq:'dudas/preguntas-frecuentes.md'},
   ]},
  {id:4,name:'Entrega y Cierre',accent:'green',
   classes:[
    {n:11,title:'Testing con pytest',desc:'TestClient, httpx, fixtures, cobertura, TDD.',
     tags:['pytest','TestClient','Coverage','TDD'],dir:'clase-11-testing-pytest',
     slides:'html/index.html',doc:'clase-11-testing-pytest.md',
     example:'ejemplo-guiado/ejemplo-testing-api.md',
     ex:'ejercicios/ejercicios-clase-11.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:12,title:'Despliegue en Render + Supabase',desc:'pydantic-settings, Supabase, Render, CI/CD.',
     tags:['Render','Supabase','CI/CD','Python'],dir:'clase-12-despliegue-render-supabase',
     slides:'html/index.html',doc:'clase-12-despliegue-render-supabase.md',
     example:'ejemplo-guiado/ejemplo-despliegue.md',
     ex:'ejercicios/ejercicios-clase-12.md',faq:'dudas/preguntas-frecuentes.md'},
    {n:13,title:'Proyecto Integrador',desc:'Sistema de Gestión Académica: M:N, paginación, PUT, tests.',
     tags:['Integrador','M:N','Paginación','Deploy'],dir:'clase-13-proyecto-integrador',
     slides:'html/index.html',doc:'clase-13-proyecto-integrador.md',
     example:'ejemplo-proyecto-integrador.md',
     ex:'ejercicios-clase-13.md',faq:'preguntas-frecuentes.md'},
   ]},
];

const RESOURCES = [
  {cat:'FastAPI',links:[
    {l:'Documentación oficial',u:'https://fastapi.tiangolo.com/'},
    {l:'Tutorial completo',u:'https://fastapi.tiangolo.com/tutorial/'},
    {l:'Guía avanzada',u:'https://fastapi.tiangolo.com/advanced/'},
    {l:'Despliegue',u:'https://fastapi.tiangolo.com/deployment/'},
  ]},
  {cat:'Pydantic',links:[
    {l:'Documentación oficial',u:'https://docs.pydantic.dev/'},
    {l:'Validadores',u:'https://docs.pydantic.dev/latest/concepts/validators/'},
    {l:'Configuración',u:'https://docs.pydantic.dev/latest/api/config/'},
  ]},
  {cat:'SQLAlchemy',links:[
    {l:'Documentación ORM',u:'https://docs.sqlalchemy.org/'},
    {l:'Quick Start',u:'https://docs.sqlalchemy.org/en/20/orm/quickstart.html'},
    {l:'Relaciones',u:'https://docs.sqlalchemy.org/en/20/orm/relationships.html'},
    {l:'Alembic',u:'https://alembic.sqlalchemy.org/'},
  ]},
  {cat:'Autenticación',links:[
    {l:'Introducción a JWT',u:'https://jwt.io/introduction'},
    {l:'Seguridad FastAPI',u:'https://fastapi.tiangolo.com/tutorial/security/'},
    {l:'passlib',u:'https://passlib.readthedocs.io/'},
  ]},
  {cat:'Infraestructura',links:[
    {l:'Render Docs',u:'https://render.com/docs'},
    {l:'Supabase Docs',u:'https://supabase.com/docs'},
    {l:'FastAPI Deployment',u:'https://fastapi.tiangolo.com/deployment/'},
    {l:'Uvicorn Settings',u:'https://www.uvicorn.org/settings/'},
  ]},
  {cat:'Estándares',links:[
    {l:'MDN HTTP',u:'https://developer.mozilla.org/es/docs/Web/HTTP'},
    {l:'OWASP API Security',u:'https://owasp.org/API-Security/'},
    {l:'Python Packaging',u:'https://packaging.python.org/'},
  ]},
];
